name: 'Webex_PR_Notification'
description: 'Send a Webex Notification to all pull request reviewers'
author: 'George Ekow-Daniels'
branding:
  icon: 'eye'
  color: 'blue'

runs:
    - name: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: run
      run:  node webex.js