name: 'Webex_PR_Notification'
description: 'Send a Webex Notification to all pull request reviewers'
author: 'George Ekow-Daniels'
branding:
  icon: 'eye'
  color: 'blue'

runs:
    - using: node22
      run:  node webex.js